name: CI (Ubuntu + macOS)

on: [push]

jobs:
  build:
    name: ${{ matrix.plat.name }} Build
    runs-on: ${{ matrix.plat.os }}
    strategy:
      fail-fast: false
      matrix:
        plat:
          - { os: ubuntu-latest, name: Ubuntu }
          - { os: macos-latest,  name: macOS }

    steps:
      - uses: actions/checkout@v5

      - name: Download submodules
        shell: bash
        run: git submodule update --init --recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install the project
        run: |
          uv sync --locked --extra dev
          uv build

  test:
    name: ${{ matrix.plat.name }} Tests
    runs-on: ${{ matrix.plat.os }}
    needs: build
    strategy:
      fail-fast: false
      matrix:
        plat:
          - { os: ubuntu-latest, name: Ubuntu }
          - { os: macos-latest,  name: macOS }

    steps:
      - uses: actions/checkout@v5

      - name: Download submodules
        shell: bash
        run: git submodule update --init --recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install the project
        run: uv sync --locked --extra dev

      - name: Install coverage tools
        run: uv pip install coverage coveralls

      - name: Run tests with coverage
        env:
          DUMMY_SPARK: 1
        run: uv run coverage run --source=drudge -m pytest tests

      - name: Upload coverage to Coveralls (Ubuntu only)
        if: ${{ always() && matrix.plat.os == 'ubuntu-latest' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: uv run coveralls --service=github

