name: Ubuntu

on: [push, pull_request]

jobs:
  build:
    name: Ubuntu Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Download submodules
      shell: bash
      run: |
        git submodule update --init --recursive

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"

    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Install the project
      run: |
        uv sync --locked --extra dev
        uv build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ubuntu-build
        path: |
          .venv/
          dist/
        retention-days: 1

  test:
    name: Ubuntu Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v5

    - name: Download submodules
      shell: bash
      run: |
        git submodule update --init --recursive

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"

    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: ubuntu-build

    - name: Install coverage tools
      run: |
        uv pip install coverage coveralls

    - name: Run tests with coverage
      env:
        DUMMY_SPARK: 1
      run: uv run coverage run --source=drudge -m pytest tests

    - name: Upload coverage to Coveralls
      if: always()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: uv run coveralls --service=github
 
